### ISSUE TITLE
sMap freezing during stepping stone analysis

### ISSUE THREAD

**Issue by jezierskim** [arklumpus/sMap#1]
Hi,

I am following the sMap tutorial on a MacOs Big Sur 11.4 desktop. Running stepping-stone analyses from the tutorial (5.6 and 5.7) I have found that the analysis almost every time stops some time while performing the chain.

I managed to get it to run once by opening a second terminal window and running it there while doing 5.6, but that fix failed with 5.7.

Output of top in the terminal tells me that while the analysis is running sMap is using >400% CPU and while it freezes it stops at 99-100%.

Do you have any suggested fixes, or need more information?

With best wishes,
Michal

**Comment by jezierskim** [comment]
Seems what I have missed is interrupting the chain - that seems to fix everything. Only worked that out with the GUI, sorry for trouble. For the future, is that an appopriate way of dealing with this?

**Comment by arklumpus** [comment]
Hi! Thank you for the interest in sMap!

I believe there is a very annoying deadlock condition somewhere, that only manifests itself when the analysis is simple enough and the computer is fast enough (which makes it very hard to debug, because the debug code slows down the program enough so that the issue does not happen).

I have created a new version of sMap with a watchdog timer that detects this and restarts the chains, but the hard drive of my Mac failed and I haven't yet been able to create the Mac installer (the fact that I'm also working on my thesis at the same time doesn't help 😪).

You can interrupt the analysis in the command line version by pressing `CTRL`+`C` (this doesn't kill the program - it does the same thing as the `Interrupt` button in the GUI version), or, if you have started the program with the `--poll` option, by creating a file called `<outputprefix>.interrupt` (which is useful if you're running in a headless environment, e.g. on a remote server).

Let's leave this issue open, and I will update you when I release the new version!

**Comment by arklumpus** [comment]
This should be fixed in version 1.0.7!
